
export const products = [
    {
        id: 1,
        name: "The Cloud Sofa",
        category: "Living Room",
        price: 1299,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1770&q=80",
        description: "Experience the feeling of floating on a cloud with our plush, deep-seated sofa.",
    },
    {
        id: 2,
        name: "Minimalist Oak Chair",
        category: "Dining",
        price: 249,
        image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Solid oak construction with a curved backrest for ergonomic comfort.",
    },
    {
        id: 3,
        name: "Artisan Coffee Table",
        category: "Living Room",
        price: 499,
        image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "Handcrafted from reclaimed wood, each piece tells a unique story.",
    },
    {
        id: 4,
        name: "Velvet Accent Chair",
        category: "New Arrivals",
        price: 399,
        image: "https://images.unsplash.com/photo-1567538096630-e997191f7d5d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Luxurious velvet upholstery available in jewel tones.",
    },
    {
        id: 5,
        name: "Industrial Bookshelf",
        category: "Office",
        price: 599,
        image: "https://images.unsplash.com/photo-1594620302200-9a72930e6dd1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "A sturdy mix of metal and wood for your collection.",
    },
    {
        id: 6,
        name: "Ceramic Vase Set",
        category: "Decor",
        price: 89,
        image: "https://images.unsplash.com/photo-1581783342308-f792ca11df53?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Hand-thrown ceramic vases in earthy tones.",
    },
    {
        id: 7,
        name: "Luxe Leather Sofa",
        category: "Most Popular",
        price: 2499,
        image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Premium top-grain leather that ages beautifully.",
    },
    {
        id: 8,
        name: "Modern Nightstand",
        category: "Bedroom",
        price: 199,
        image: "https://images.unsplash.com/photo-1532372320572-cda25653a26d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Sleek and functional with soft-close drawers.",
    },
    {
        id: 9,
        name: "Woven Pendant Light",
        category: "New Arrivals",
        price: 149,
        image: "https://images.unsplash.com/photo-1513506003013-d5316ca97527?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Natural rattan weave creates beautiful light patterns.",
    },
    {
        id: 10,
        name: "Teak Outdoor Set",
        category: "Outdoor",
        price: 1899,
        image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Weather-resistant teak perfect for patio living.",
    },
    {
        id: 11,
        name: "Abstract Area Rug",
        category: "Decor",
        price: 299,
        image: "https://images.unsplash.com/photo-1575414003591-ece8d0416c7a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Hand-tufted wool blend with a modern abstract design.",
    },
    {
        id: 12,
        name: "Mid-Century Desk",
        category: "Office",
        price: 699,
        image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        description: "Iconic mid-century silhouette with ample workspace.",
    },
];

export const navigation = [
    { name: "Living Room", href: "#" },
    { name: "Dining", href: "#" },
    { name: "Bedroom", href: "#" },
    { name: "Office", href: "#" },
    { name: "Decor", href: "#" },
];
